version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:postgresql://db:5432/postgres",
            "spring.datasource.username" : "postgres",
            "spring.datasource.password" : "postgres",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.datasource.driver-class-name" : "org.postgresql.Driver"
          }'
    stdin_open: true
    tty: true
  db:
    image: 'postgres:14-alpine'
    container_name: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql
volumes:
  db:
